language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

script:
     npm run build
     npm run coveralls

branches:
  only:
    - develop-5

after_script:
 - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info  && npm run clear
    
